database:
  source_table: "users_raw"
  target_table: "users_masked"

mappings:
  - source: "full_name"
    target: "full_name"
    method: "fake_name"
  - source: "email"
    target: "email"
    method: "fake_email"
  - source: "salary"
    target: "salary_status"
    method: "salary_bucket"  # NOVI METOD

anonymization:
  locale: "de_DE"
  use_ascii: true